# Generated by Django 5.0.3 on 2024-03-27 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_doctor_patient_procedure_visit_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='additional_information',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='additional_information',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='price',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='note',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='visit_date',
        ),
        migrations.AddField(
            model_name='doctor',
            name='additional_info',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='additional_info',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_date_time',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='visit',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='patient',
        ),
        migrations.AlterField(
            model_name='visit',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.procedure'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'PLANNED'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.specialization'),
        ),
        migrations.AddField(
            model_name='visit',
            name='doctor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.patient'),
            preserve_default=False,
        ),
    ]
