# Generated by Django 5.0.3 on 2024-04-02 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_visit_visit_date_time_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='visit',
        ),
        migrations.AddField(
            model_name='visit',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit', to='api.schedule'),
        ),
    ]
