# Generated by Django 5.0.3 on 2024-04-02 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_schedule_visit_visit_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='doctor',
        ),
    ]
